[package]
name = "register_bank"
version = "0.1.0"
authors = ["Kris Chambers <kris.chambers@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
model = { path = "../model" }
data = { path = "../data" }