[workspace]

members = [
    "emulator",
    "data",
    "framebuffer",
    "model",
    "register_bank",
    "memory",
    "program_counter",
    "vm",
    "instruction",
    "keyboard",
    "rom_library",
]